name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.12'
          - 'coqorg/coq:8.11'
          - 'coqorg/coq:8.10'
        opam_file:
          - 'coq-chapar.opam'
          - 'coq-chapar-stores.opam'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: ${{ matrix.opam_file }}
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Install dependencies"
              opam pin add -n -y -k path coq-chapar $WORKDIR
              opam pin add -n -y -k path coq-chapar-stores $WORKDIR
              opam update -y
              opam install -y -j 2 $PACKAGE --deps-only
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
